### ISSUE TITLE
Non-blocking push

### ISSUE THREAD

**Issue by utopos** [elliotekj/off_broadway_memory#4]
Hello Team,

first of all: great job on this library!

 I wanted to ask (not sure whether this is an "issue") whether non-blocking "push" to the Buffer Genserver would make sense?

 For example, I am writing an analytics for a url shortening server: every time a url gets resolved from hash (ex my.ly/xyc -> www.onet.pl), I would like to push to my Broadway pipeline some metadata (time of the resolution, browser headers). I would not like to make my analytics queue genserver (Buffer) to block the resolution action. Would "cast" version of the "push" make sense in this situation?

Best,
Kuba

**Comment by elliotekj** [comment]
Hey @utopos,

Yes, there's definitely room for this. I would add a `push_async/2` type function to `Buffer` rather than replacing the functionality of the current `push/2`.

Let me know if you want to pick this up; if not, I'll get it in this week.

Cheers,
Elliot

**Comment by utopos** [comment]
Hi Elliot,

Thanks for a quick reply. Yes I can definitely do it. How shall we proceed?

Best,
Jakub

**Comment by elliotekj** [comment]
Perfect!

You might want to move the existing bulk push logic <https://github.com/elliotekj/off_broadway_memory/blob/main/lib/off_broadway_memory/buffer.ex#L53-L60> to a new function as it’ll be reusable between the call and cast handlers.

As with the existing push function, make sure that both single messages and lists of messages are supported.

If you could then just make sure the your new function is spec’d, documented and tested that would be great.

Once you’re happy, open an PR and we’ll run through it, get it merged and publish a release.

Let me know if you have any questions :)
