### ISSUE TITLE
Implement `prepare_for_start`  Producer callback

### ISSUE THREAD

**Issue by utopos** [elliotekj/off_broadway_memory#5]
Hello Team, 

One more question to ask: would be a good idea for the buffer to be started withing the pipeline supervision tree?  

Rationale: when buffer is not started or there's a mismatch between buffer names, it will bring the pipeline down. 

Potential approach: implement the `prepare_for_start` callback that will add child spec of the buffer to the Broadway supervision tree and align the buffer names in the local Registry.

The Producer behaviour provides a callback for this:

> The goal of this callback is to manipulate the general topology options, if necessary at all, and introduce any new child specs that will be started before the producers supervisor in Broadway's supervision tree. Broadway's supervision tree is a rest_for_one supervisor (see the documentation for [Supervisor](https://hexdocs.pm/elixir/Supervisor.html)), which means that if the children returned from this callback crash they will bring down the rest of the pipeline before being restarted.

I already implented it in my local fork and works. I can contribute if you think this change makes sense.

**Comment by elliotekj** [comment]
Definitely something to consider. I'll have a play with this this week and update this ticket when I have more thoughts.
